### ISSUE TITLE
Can't reload when Unable to load class 'Class 'com.android.build.api.attributes.BuildTypeAttr$Impl' not found in class loader

### ISSUE THREAD

**Issue by adamglin0** [JetBrains/compose-hot-reload#421]
**Describe the bug**

When using the IDE's save to reload, there is a probability of encountering the following error, which prevents reloading. It can only be resolved by restarting the program. However, after a period of time, the same error will still occur.

```
Unable to load class 'Class 'com.android.build.api.attributes.BuildTypeAttr$Impl' not found in class loader 'InstrumentingVisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:]:buildSrc[:]:root-project[:](export)})' of type 'org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader'.'
Class 'com.android.build.api.attributes.BuildTypeAttr$Impl' not found in class loader 'InstrumentingVisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:]:buildSrc[:]:root-project[:](export)})' of type 'org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader'.

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

```
**To Reproduce**

I have not found a stable method for reproduction, but using command+s will occur with a probability.

**Expected behavior**

**Environment**
 - OS: [e.g. MacOS, Windows, Ubuntu] Macos
 - Kotlin version: [e.g. `2.2.0`] 2.2.21
 - Compose Multiplatform version: [e.g. `1.8.2`] 1.10.0-beta01
 - Compose Hot Reload version: [e.g. `1.0.0-beta05`] I remember both version 1.0.0-rc01 and 1.0.0-rc02 had this issue.
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2025.2, Android Studio 2025.1] IntellijIDEA 2025.4
   - Kotlin Multiplatform plugin version (if it is installed) [e.g. `0.9-253.14012-IJ_CE-0`] 0.9.252.27397-IJ-134
 - Other relevant context

**Comment by adamglin0** [comment]
There is a clue that, under normal circumstances, there are 2 running tasks

<img width="595" height="50" alt="Image" src="https://github.com/user-attachments/assets/8bf6c64d-0c41-4b85-a3ff-932857cc822f" />

However, when this issue occurs, there will be 2 reload tasks

**Comment by AbdullinAM** [comment]
Thank you for reporting! Can you, please, clarify a couple of things to help us reproduce the issue:

> It can only be resolved by restarting the program

So just the regular restart helps? You don't need to restart gradle daemons or anything else?

> However, when this issue occurs, there will be 2 reload tasks

Have you noticed some patterns on when the second reload task appears? E.g. maybe its when you send two back-to-back reload requests? 

Can you try to check the output of both `reload` tasks when this happens again? Is the first one still running when the second one starts? Does the error appear in the first or the second (or both) tasks?

**Comment by AbdullinAM** [comment]
KMP 0.9.252.27397-IJ-134 spawns a `reload` task with a separate window on every "Save and reload" action, i.e. on every `Ctrl + S`. So if two reloads are triggered with an overlap, one running `reload` gradle task could have potentially invalidated some caches for another one? 

Can you try to reproduce this by intentionally spawning several reload tasks at the same time? Or, if your project is open-source, a link to it, so that we can reproduce and check this ourselves?

The issue with multiple 'reload' tasks was already fixed and will be available in the KMP plugin versions `253.*`

**Comment by adamglin0** [comment]
> So just the regular restart helps? You don't need to restart gradle daemons or anything else?

Most of the time, restarting will solve the problem, but sometimes you have to re-sync Gradle.

> However, when this issue occurs, there will be 2 reload tasks

I have noticed many times that when errors occur, there are two reload tasks, but sometimes even with just one reload task, errors still occur.

<img width="880" height="298" alt="Image" src="https://github.com/user-attachments/assets/f2de4199-63cb-41b0-a614-07a37f4afd6c" />

>  Can you try to check the output of both `reload` tasks when this happens again? Is the first one still running when the 
second one starts? Does the error appear in the first or the second (or both) tasks?

If two reload tasks appear, I will continue updating.

**Comment by adamglin0** [comment]
> KMP 0.9.252.27397-IJ-134 spawns a `reload` task with a separate window on every "Save and reload" action, i.e. on every `Ctrl + S`. So if two reloads are triggered with an overlap, one running `reload` gradle task could have potentially invalidated some caches for another one?
> 
> Can you try to reproduce this by intentionally spawning several reload tasks at the same time? Or, if your project is open-source, a link to it, so that we can reproduce and check this ourselves?
> 
> The issue with multiple 'reload' tasks was already fixed and will be available in the KMP plugin versions `253.*`

If two reload tasks appear, but in reality only one task is running, no error will occur. Sometimes the same error occurs even with only one reload task. I will continue trying to make it reproducible.

**Comment by cn-tre-lfp** [comment]
I can now confirm that it was entirely caused by multiple reload tasks.

**Comment by adamglin0** [comment]
The final investigation revealed that the error was caused by multiple reload tasks running simultaneously. Whenever two reload tasks occurred concurrently, it could potentially break the hot reload functionality.

**Comment by sellmair** [comment]
Then I am happy to share that newer versions of the Kotlin Multiplatform plugin changed the way they issue reloads and properly put things into a queue 👍

**Comment by AbdullinAM** [comment]
Fixed version of Kotlin Multiplatform plugin is now available for both IDEs, so I'm closing the issue
